### ISSUE TITLE
Update and publish DE R notebook

### ISSUE THREAD

**Issue by georgiesamaha** [Sydney-Informatics-Hub/rnaseqOct23_Testing#10]
- Review and update contents of Rmd as needed
- Put notebook on github for others to use

**Comment by nandan75** [comment]
I have made the following small updates to the R-markdown file    
I need to **reflect the above changes to the Day2- web-pages**


(1) **REMOVE** from Web-page https://sydney-informatics-hub.github.io/rna-seq-pt2-quarto/notebooks/0.3_nextflow_to_RStudio.html#set-your-working-directory  

```{r}
# Set your working directoryWe will set our working directory to the path that contains our count matrix file.   
# Run the next code block by clicking the green arrow.   
setwd("/home/training/base_directory/working_directory").  

```

(2) Where will be the FULL_count_matrix.txt" file located? We need to download it prior to reading it in RStudio


```{r}
# Read in the full count matrix file
# This file was included in the data we downloaded for Part 1
```{r}
counttable_original <- read.delim("FULL_count_matrix.txt", 
                                header = T, 
                                row.names = 1)
```

(3) Data format is very important to ensure that functions read and analyse data correctly!Check .Rmd for the updated text
- #  View the count table with the code below
```{r}
View(counttable)
```

- **At the end of section** - https://sydney-informatics-hub.github.io/rna-seq-pt2-quarto/notebooks/0.3_nextflow_to_RStudio.html#experimental-design-metadata # View the meta dataframe with the code below
```{r}
View(meta)
```

**Comment by georgiesamaha** [comment]
@nandan75 please save rmd to an SIH repo and link in the [bioinformatics page](https://github.com/Sydney-Informatics-Hub/Bioinformatics#notebook-reproducible-notebooks). Ensure the repo has a descriptive readme.

**Comment by georgiesamaha** [comment]
* README to contain instructions for downloading it `git clone`, usage and version of RStudio 
* Cleaned rmd, no typos, correct headers 
* Add a box with notebook and description to reproducible notebook section of bioinformatics github repo

**Comment by nandan75** [comment]
Added https://github.com/Sydney-Informatics-Hub/rnaseq_DE_Day2_1023.git and 

linked to


https://github.com/Sydney-Informatics-Hub/Bioinformatics/blob/master/README.md#notebook-reproducible-notebooks
