### ISSUE TITLE
Upload necessary files to CVMFS

### ISSUE THREAD

**Issue by georgiesamaha** [Sydney-Informatics-Hub/rnaseqOct23_Testing#14]
- [x] Identify files to go on CVMFS and in what structure 
- [x] Upload files to sharepoint and create shareable link 
- [x] Contact AARnet to upload files via sharepoint link

**Comment by nandan75** [comment]
- Identify files to go on CVMFS and in what structure
   - Singularity container .sif
   - A backup commands.readme file with all commands
   - All input fastqs
   - References

**Comment by nandan75** [comment]
Email sent to AARNET with regards to details about files to be uploaded to cvmfs

**Comment by georgiesamaha** [comment]
@nandan75 Remove the email comment from here please, this is publicly visible.

**Comment by nandan75** [comment]
Uploaded by Alex

@georgiesamaha  Are you planning to test Day 1 with cvmfs or do you want me to?

**Comment by georgiesamaha** [comment]
Will do now

**Comment by georgiesamaha** [comment]
@nandan75 I ran the QC command with updated cvmfs path:

- Fasta works 
- GTF works 
- Salmon and star indexes work
- samplesheet path works but paths for samples are broken (my mistake) 
- Fastq files all in place

Could you please arrange for samplesheet.csv file on IntroRNAseq_1023 cvmfs repo to be updated to the following: 

```bash
sample,fastq_1,fastq_2,strandedness
SRR3473989,/cvmfs/data.biocommons.aarnet.edu.au/training_materials/SIH_training/IntroRNAseq_1023/fastq/SRR3473989_selected.fastq.gz,,unstranded
SRR3473988,/cvmfs/data.biocommons.aarnet.edu.au/training_materials/SIH_training/UnlockNfcore_1023/fastq/SRR3473988_selected.fastq.gz,,unstranded
SRR3473987,/cvmfs/data.biocommons.aarnet.edu.au/training_materials/SIH_training/UnlockNfcore_1023/fastq/SRR3473987_selected.fastq.gz,,unstranded 
SRR3473986,/cvmfs/data.biocommons.aarnet.edu.au/training_materials/SIH_training/UnlockNfcore_1023/fastq/SRR3473986_selected.fastq.gz,,unstranded 
SRR3473985,/cvmfs/data.biocommons.aarnet.edu.au/training_materials/SIH_training/UnlockNfcore_1023/fastq/SRR3473985_selected.fastq.gz,,unstranded 
SRR3473984,/cvmfs/data.biocommons.aarnet.edu.au/training_materials/SIH_training/UnlockNfcore_1023/fastq/SRR3473984_selected.fastq.gz,,unstranded
```

**Comment by nandan75** [comment]
I will confirm the .Rmd file (all working) for any typos in next 10 mins and email Alex about this.

**Comment by nandan75** [comment]
Sent email to Alex about the required changes to samplesheet.csv

**Comment by georgiesamaha** [comment]
Have these changes been made/tested?

**Comment by nandan75** [comment]
**I checked the samples sheet** which now looks correct and  checked that the files are in place (which was already placed properly).

ls -lt /cvmfs/data.biocommons.aarnet.edu.au/training_materials/SIH_training/IntroRNAseq_1023/fastq

**I have not** run the nextflow/nfcore commands.. after the sample-sheet update

sample,fastq_1,fastq_2,strandedness
SRR3473989,/cvmfs/data.biocommons.aarnet.edu.au/training_materials/SIH_training/IntroRNAseq_1023/fastq/SRR3473989_selected.fastq.gz,,unstranded
SRR3473988,/cvmfs/data.biocommons.aarnet.edu.au/training_materials/SIH_training/IntroRNAseq_1023/fastq/SRR3473988_selected.fastq.gz,,unstranded
SRR3473987,/cvmfs/data.biocommons.aarnet.edu.au/training_materials/SIH_training/IntroRNAseq_1023/fastq/SRR3473987_selected.fastq.gz,,unstranded
SRR3473986,/cvmfs/data.biocommons.aarnet.edu.au/training_materials/SIH_training/IntroRNAseq_1023/fastq/SRR3473986_selected.fastq.gz,,unstranded
SRR3473985,/cvmfs/data.biocommons.aarnet.edu.au/training_materials/SIH_training/IntroRNAseq_1023/fastq/SRR3473985_selected.fastq.gz,,unstranded
SRR3473984,/cvmfs/data.biocommons.aarnet.edu.au/training_materials/SIH_training/IntroRNAseq_1023/fastq/SRR3473984_selected.fastq.gz,,unstranded

**Comment by georgiesamaha** [comment]
I have, I already confirmed with you

**Comment by nandan75** [comment]
ok .. 

So all done here . 
 Samplesheet error corrected.

Everything else tested.

Please close the ticket.
