### ISSUE TITLE
Resolve Nimbus loop issue

### ISSUE THREAD

**Issue by nandan75** [Sydney-Informatics-Hub/rnaseqOct23_Testing#16]
- Find solution for addressing this problem #15 

- [x] @georgiesamaha  Check with Pawsey Helpdesk

**Comment by georgiesamaha** [comment]
Contacted Pawsey

**Comment by nandan75** [comment]
Thanks

**Comment by nandan75** [comment]
Correspondence with  Pawsey Nimbus Team
 
- It looks like a common occurrence these days with Singularity trying to use more than one loop device so the solution would be to increase the loop devices. 
- This previous solution has worked : [https://support.pawsey.org.au/documentation/display/US/Using+Containers#UsingContainers-Commonissues](https://protect-au.mimecast.com/s/zymaCWLVXkU68GBODF642Ve?domain=support.pawsey.org.au)
- Pawsey will increase the number of loop devices as above before cloning the instances.

**Comment by nandan75** [comment]
Since the issue as such has now been clearly identified by Pawsey and we are able to work-around it during the workshop development, I will close this ticket.

But I will open a new ticket  for "Check with Pawsey - Increase the number of loop devices as above before cloning the instances"
