### ISSUE TITLE
Create multiple instances from a final image

### ISSUE THREAD

**Issue by nandan75** [Sydney-Informatics-Hub/rnaseqOct23_Testing#47]

**Comment by nandan75** [comment]
We need to confirm with Audrey that the loop related issue has been rectified . I observed the same error yesterday when I created a new instance and ran RStudio server on it. The issue was sorted by using the usual workaround commands

**Comment by georgiesamaha** [comment]
@nandan75 going to leave this to you to handle. You have admin rights on the instance dashboard

**Comment by georgiesamaha** [comment]
As discussed via email, the issue will not be rectified until we create new instances.

**Comment by nandan75** [comment]
ok I will go back to this one in the afternoon and check

**Comment by nandan75** [comment]
What happens now?

1)  **Audrey** increases the loop numbers in the base image
2) **I/you** create the directory structure ?
3) **Audrey** spins the VMs based on the image form 1) and 2) ?

**Comment by nandan75** [comment]
Nandan to create a final VM to be used as template - for Pawsey , today

@georgiesamaha  Can you confirm if anything has changed/update for Day1 and Data related to Day1? 
Else I will pick up the datasets from https://unisyd.sharepoint.com/:f:/r/teams/SydneyInformaticsHub2/Shared%20Documents/1%20SIH%20Central%20Document%20Repository/Projects/1%20JIRA%20projects/PIPE-4228%20Australian%20BioCommons%20-%20RNAseq%20training/Data?csf=1&web=1&e=HGhSCU 




(1) Please confirm on the directory structure and its contents


**/home/training/**
                    - **Day_1**
                    - **Day_2** 
                        -- rnaseq_DE_analysis_Day2.Rmd
                        -- FULL_count_matrix.txt
                    - **Data**
                        --fastqs
                        -- mm10_reference
                        -- samplesheet
                        -- WBS-Mouse-QC
                        -- WBS-Mouse-results

(2) On the test VM the path is 
**/home/ubuntu**

** Will Audrey take care that the path is changed to **/home/training** for the clones?

**Comment by georgiesamaha** [comment]
## nf-core code base

Day 1 directory needs to house nf-core/rnaseq code base. Follow [directions](https://github.com/Sydney-Informatics-Hub/rnaseqOct23_Testing/blob/main/Scripts/Day1/Runtime-testing.md#use-of-nf-core-tools-for-downloading-code-base-and-containers) to download. 

1. Download nf-core tools 

```bash
sudo pip install nf-core
```

2. Download the rnaseq pipeline code

```bash
nf-core download
```

Follow the prompts: 
* Pipeline name: rnaseq
* Release/branch: 3.12.0
* Include institutional configs: n 
* Download software container images: singularity
* Define $NXF_SINGULARITY_CACHEDIR for a shared Singularity image download folder: n
* Compression type: none 

The output directory will be `nf-core-rnaseq_3.12.0`. Inside is the code base `3_12_0` and containers `singularity-images`. Ensure this is sitting at `/home/ubuntu/Day_1/nf-core-rnaseq_3.12.0` in your VM to be cloned. Once the VMs have been cloned this path will be `/home/training/Day_1/nf-core-rnaseq_3.12.0`

## Data directory

Data directory can be symlinked from what you put on CVMFS last week. Do not download anything from Sharepoint onto the VMs. If symlinking will not port across in the cloned machines, don't worry about it. I will get participants to do this at the start of day 1. 

## Training VM paths 

Yes, Nimbus training VMs always have the home directory path set as `/home/training` 

Once this workshop is over, can you please write an operating procedure outlining the protocol for training VM set up and communication with Pawsey so we can recall these details for next workshop.

**Comment by nandan75** [comment]
ok will proceed 

Create a new VM
Place all Direcories/files 
Test - 
       Day 1 
       Day 2

Clean the VM of the outputs and the proceed.

Cheers


Nandan

**Comment by georgiesamaha** [comment]
Can you please ensure any hidden .nextflow .git .quarto .anything else are removed.

**Comment by nandan75** [comment]
sure
