### ISSUE TITLE
Replace IGV exercise for alignment visualisation

### ISSUE THREAD

**Issue by nandan75** [Sydney-Informatics-Hub/rnaseqOct23_Testing#50]
- [x] Find chr5 bams from 2022
- [x] Create images of 2 regions 
- [x] Adjust question to ask which image can be used for sample identification

**Comment by nandan75** [comment]
Data folder for IGV exercise from Sept22 on [sharepoint](https://unisyd.sharepoint.com/:f:/r/teams/SydneyInformaticsHub2/Shared%20Documents/1%20SIH%20Central%20Document%20Repository/Projects/1%20JIRA%20projects/PIPE-4228%20Australian%20BioCommons%20-%20RNAseq%20training/Gtf2ird1_flanking_region?csf=1&web=1&e=7LHV9e)

**Comment by georgiesamaha** [comment]
@nandan75 can you take a look and let me know what you think of this? 
https://sydney-informatics-hub.github.io/rnaseq-workshop-2023/notebooks/1.4_alignquant.html#visualising-alignments

**Comment by nandan75** [comment]
sure I will now

**Comment by nandan75** [comment]
Great. Looks good to me
