### ISSUE TITLE
Day 2: test use of cvmfs with Rstudio image

### ISSUE THREAD

**Issue by georgiesamaha** [Sydney-Informatics-Hub/rnaseqOct23_Testing#7]
Can we use count matrix hosted on CVMFS for day 2 or will we need to download it to VM?

**Comment by nandan75** [comment]
I did a primary test to use the rstudio from cvmfs path and it works

mkdir -p /tmp/rstudio-server

PASSWORD='abc' singularity exec \
    -B /tmp/rstudio-server:/var/lib/rstudio-server \
    -B /tmp/rstudio-server:/var/run/rstudio-server \
    -B /home/ubuntu/working_directory/Day-2:/home \
    **/cvmfs/data.biocommons.aarnet.edu.au/training_materials/SIH_training/IntroRNAseq_1023/rstudio_4.1.0.sif** \
    rserver --auth-none=0 --auth-pam-helper-path=pam-helper --server-user ubuntu


I will try the symlinks

**Comment by georgiesamaha** [comment]
Works without issue.
